[package]
name = "tmps-core"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl = "0.10"
rand = "0.8"
thiserror = "1"
sha2 = "0.10"
hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
chrono = { version = "0.4", features = ["serde"] }